### ISSUE TITLE
Switch to Unix socket

### ISSUE THREAD

**Issue by shivaraj-bh** [juspay/todo-app#15]
Allowing development environment and CI to be truly local to project directory (no global state, i.e connecting to a TCP port)

`postgrest` supports Unix socket to start the REST API server ([see](https://docs.postgrest.org/en/stable/references/configuration.html#server-unix-socket)) and to connect to `postgres` ([see](https://docs.postgrest.org/en/stable/references/configuration.html#uri-format))

**Comment by srid** [comment]
Let's do this as part of `Part 4`, and we can describe the general workflow of services-flake here as well ("Use Unix socket wherever possible").
